resilience4j.bulkhead:
    configs:
        default:
          maxConcurrentCalls: 25
          maxWaitDuration: 0
    instances:
        bulkheadA:
          maxConcurrentCalls: 3
          maxWaitDuration: 6000

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadB:
      maxThreadPoolSize: 5
      coreThreadPoolSize: 3
      queueCapacity: 1
      keep-alive-duration: 3000
      writableStackTraceEnabled: true
