resilience4j.bulkhead:
    configs:
        default:
          maxConcurrentCalls: 25
          maxWaitDuration: 0
    instances:
        bulkheadA:
          maxConcurrentCalls: 1
          maxWaitDuration: 600000

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadB:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 10
      keep-alive-duration: 3000
      writableStackTraceEnabled: true


bucket4j:
  version: 1
  capacity: 5
  refill:
    period:
      second: 10
    token: 3
    
